disabled_rules:
  - trailing_comma
allow_zero_lintable_files: false
check_for_updates: true
force_cast: warning
force_try:
  severity: warning
line_length: 120
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  allowed_symbols: ["_"]
  min_length:
    error: 2
  excluded:
    - x
    - y
    - z
    - up
    - id
    - URL

custom_rules:
  cubiomes_internal_use: # rule identifier
    excluded:
      - "CubiomesKit/*.swift" # regex that defines paths to exclude during linting. optional
    name: "External CubiomesInternal Usage" # rule name. optional.
    regex: "(import CubiomesInternal)" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    message: "Don't import CubiomesInternal directly outside of CubiomesKit." # violation message. optional.
    severity: warning # violation severity. optional.

reporter: "xcode"