opt_in_rules:
  - explicit_init
disabled_rules:
  - trailing_comma

allow_zero_lintable_files: false
check_for_updates: true

explicit_init:
  severity: warning
  include_bare_init: true
force_cast: warning
force_try:
  severity: warning
line_length: 120
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  allowed_symbols: ["_"]
  min_length:
    error: 2
  excluded:
    - x
    - y
    - z
    - up
    - id
    - URL

custom_rules:
  prefer_is_not_empty:
    name: "Prefer Bedrock isNotEmpty"
    regex: "(\\![a-zA-Z0-9\\_\\.]+\\.isEmpty)"
    capture_group: 0
    message: "Prefer to use the isNotEmpty property from Bedrock."
    severity: warning
reporter: "xcode"
